music_spot/urls.py
from django.urls import path

from . import views

app_name = 'music_spot'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('artist/<int:pk>/',views.ArtistDetailView.as_view(),name='artist_detail'),
    path('song/<int:pk>',views.SongDetailView.as_view(),name='song_detail'),
    path('artist/',views.ArtistListView.as_view(),name='artist_list'),
    path('song/',views.SongListView.as_view(),name='song_list'),
    path('contact/',views.ContactView.as_view(),name='contact'),
]

mymusic/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music_spot/', include('music_spot.urls')),
]

music_spot/models.py
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Song(models.Model):
    artist = models.ForeignKey(Artist,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    youtube_video_id = models.CharField(max_length=20,null=True,blank=True)

    def __str__(self):
        return self.name

    def youtube_link(self):
        if self.youtube_video_id is None: return None
        return f"https://www.youtube.com/watch?v={self.youtube_video_id}"

    def youtube_embedded_link(self):
        if self.youtube_video_id is None: return None
        return f"https://www.youtube.com/embed/{self.youtube_video_id}"

music_spot/views.py
from django.shortcuts import render
from django.views import generic
from .models import Artist,Song
# from .models import Artist
# Create your views here.

class IndexView(generic.TemplateView):
    template_name = "music_spot/index.html"

class ArtistDetailView(generic.DetailView):
    model = Artist
    template_name = "music_spot/artist_detail.html"    

class SongDetailView(generic.DetailView):
    template_name = "music_spot/song_detail.html"
    model = Song

class SongListView(generic.ListView):
    template_name = "music_spot/song_list.html"
    model = Song
    def get_queryset(self):
        return Song.objects.order_by('name')

class ArtistListView(generic.ListView):
    template_name = "music_spot/artist_list.html"
    model = Artist
    def get_queryset(self):
        return Artist.objects.order_by('name')

class ContactView(generic.TemplateView):
    template_name = "music_spot/contact.html"

music_spot/templates/music_spot/artist_detail.html
{% extends 'music_spot/layout.html' %}

{% block content %}
    <h1 class="title">
        {{ artist.name }}
    </h1>
    <table class="table table-hover">
        <caption> List of songs </caption>
        <thead class ="thead-light">
        <tr><th>Song</th><th>link</th></tr>
        </thead>
        {% for song in artist.song_set.all %}
        <tr><td> <a href = {% url 'music_spot:song_detail' song.id %}>{{ song.name }}</a> </td> <td> <a target="_blank" href={{song.youtube_link}}>{{ song.youtube_link }} </a></td></tr>
        {% endfor %}
    </table>
{% endblock %}

music_spot/templates/music_spot/artist_list.html
{% extends 'music_spot/layout.html' %}

{% block content %}
    <h2>
        Click your favorite artist.
    </h2>
    <h3>
        These artists are my favorite artists.
    </h3>
    <div class="list-group">
        {% for artist in object_list %}
        <a href="{% url 'music_spot:artist_detail' artist.id %}" class="list-group-item list-group-item-action">
            {{ artist.name }}
        </a>
        {% endfor %}
    </table>
{% endblock %}

music_spot/templates/music_spot/contact.html
{% extends 'music_spot/layout.html' %}

{% block content %}
<ul>
<li> Twitter: @nikutto_ </li>
<li> Mail: nikutto[piyopiyo]outlook.com (replace [piyopiyo] with at mark.) </li>
</ul>
著作権には十分配慮しているつもりですが、問題になりうる箇所があればご連絡ください。
{% endblock %}

music_spot/templates/music_spot/detail.html
{% extends 'music_spot/layout.html' %}

{% block content %}
    <h1 class="title">
        {{ artist.name }}
    </h1>
    <table class="table table-hover">
        <caption> List of songs </caption>
        <thead class ="thead-light">
        <tr><th>Song</th><th>link</th></tr>
        </thead>
        {% for song in artist.song_set.all %}
        <tr><td> {{ song.name }} </td> <td> {{ song.youtube_link }} </td></tr>
        {% endfor %}
    </table>
{% endblock %}

music_spot/templates/music_spot/index.html
{% extends 'music_spot/layout.html' %}

{% block content %}
<h1>
Welcome.
</h1>
<div class="about">
    <h2>
    About this site
    </h2>
    This is my web page practice and for personal use.
</div>

{% endblock %}

music_spot/templates/music_spot/layout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset = "utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" text="text/css" href='/static/music_spot/css/blog.css'>
        <link rel="icon" type="image/png" href="{% static 'music_spot/icon/icon.png' %}">
    </head>
    <body>
        <div class= "container">
            <div class="headers sticky-top bg-white">
                <header class = "blog-header py-3">
                <div class="row flex-nowrap justify-content-between align-items-center">
                    <div class="col-4 text-center">
                        <a class ="blog-header-logo text-dark" href={% url 'music_spot:index' %}> MusicSpot </a>
                    </div>
                </div>
                </header>
                <div class="nav-scroller py-1 mb-2">
                    <nav class = "nav d-flex ">
                        <a class="p-2 text-muted" href = {% url 'music_spot:index' %}>Home</a>
                        <a class="p-2 text-muted" href = {% url 'music_spot:artist_list' %}>Artists</a>
                        <a class="p-2 text-muted" href={% url 'music_spot:song_list' %}>Songs</a>
                        <a class="p-2 text-muted" href={% url 'music_spot:contact' %}>Contact</a>
                    </nav>
                </div>
            </div>
            <section class = "section">
                <div class = "body_container">
                    {% block content %}
                    {% endblock %}
                </div>
            </section>
        </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    </body>
</html>

music_spot/templates/music_spot/song_detail.html
{% extends 'music_spot/layout.html' %}

{% block content %}
    <h1 class="title">
        Song Detail Page
    </h1>
    <h2 class="song_name">
        Song title: {{ song.name }}
    </h2>
    <ul class="list-group">
    <li class = "list-group-item"><a href = {% url "music_spot:artist_detail" song.artist.id %}>{{ song.artist.name }} </a></li>
    {% if song.youtube_video_id %}
    <li class = "list-group-item"><a href = {{song.youtube_link}} target="_blank">{{ song.youtube_link }}</a></li>
    {% endif %}
    </ul> 
    {% if song.youtube_video_id %}
    <iframe width="560" height="315" 
    src="{{ song.youtube_embedded_link}}" 
    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    {% endif %}
{% endblock %}

music_spot/templates/music_spot/song_list.html
{% extends 'music_spot/layout.html' %}

{% block content %}
    <h1 class="title">
        {{ artist.name }}
    </h1>
    <h2>
        Click your favorite song.

    </h2>
    <h3>
    These songs are my favorite songs.
    </h3>
    <div class="list-group">
        {% for song in object_list %}
        <a href="{% url 'music_spot:song_detail' song.id %}" class="list-group-item list-group-item-action">
            {{ song.name }} - {{song.artist.name}}
        </a>
        {% endfor %}
    </table>
{% endblock %}